FROM node:22-alpine
WORKDIR /app
RUN corepack enable
COPY ./package.json ./package.json
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./pnpm-local.yaml ./pnpm-local.yaml
COPY ./package ./package
COPY ./apps/frontend/package.json ./apps/frontend/package.json
RUN pnpm i
COPY /apps/frontend ./apps/frontend
RUN cd apps/frontend && npx tsc -b && cd ../..
RUN pnpm run dev:generate
EXPOSE 3000
CMD ["pnpm","run","start:fe"]
