FROM node:22-alpine
WORKDIR /app
RUN corepack enable
COPY ./package.json ./package.json
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./packages ./packages
COPY ./apps/http-backend/package.json ./apps/http-backend/package.json
RUN pnpm i
COPY /apps/http-backend ./apps/http-backend
RUN cd apps/http-backend && npx tsc -b && cd ../..
RUN pnpm run dev:generate
EXPOSE 3005
CMD ["pnpm","run","start:http"]
