import { Router } from "express";
import { gettRoomBySlug, room, roomChat, signin, signup } from "../controllers/auth.controllers";
import { auth } from "../middleware/auth.middlleware";
const router:Router = Router();
router.route('/signup').post(signup);
router.route('/signin').post(signin);
router.route('/room').post(auth,room);
router.route('/chats/:roomId').get(roomChat);
router.route('/room/:slug').get(gettRoomBySlug);
export default router ;
