import { Router } from "express";
import { getRoomBySlug, createRoom, roomChat, signin, signup, dashboard, roomOwnedByMe, joinRoom } from "../controllers/auth.controllers";
import { auth } from "../middleware/auth.middlleware";
const router:Router = Router();
router.route('/sign-up').post(signup);
router.route('/sign-in').post(signin);
router.route('/room').post(auth,createRoom);
router.route('/dashboard').get(auth,dashboard);
router.route('/chats/:roomId').get(auth,roomChat);
router.route('/room/:slug').get(auth,getRoomBySlug);
router.route('/roomOwned').get(auth,roomOwnedByMe);
router.route('/join/:roomId').put(auth,joinRoom);
export default router ;
